version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5431:5431  

    environment:
      - POSTGRES_DB=UpVoteHubDb
      - POSTGRES_USER=UpVoteHub
      - POSTGRES_PASSWORD=randompassword
